FROM python:3.6-stretch

#RUN apt-get update
#RUN apt-get install -y --no-install-recommends supervisor postgresql-client

RUN pip3 install virtualenv celery
RUN mkdir /home/app

#ADD ./app /home/app
#WORKDIR /home/app

#RUN bash -c "virtualenv --python=/usr/bin/python3 env && pip3 install -r requirements.txt"
#RUN mkdir /kick

#ENTRYPOINT /kick/entrypoint-web.sh


