LABEL maintainer="dub2sauce@gmail.com"
FROM nginx:latest

#RUN apt-get update
#RUN apt-get install -y --no-install-recommends curl

RUN mkdir -p /home/app/uwsgi
ADD ./conf/nginx.conf /etc/nginx/nginx.conf
ADD ./conf/3dhubs.conf /etc/nginx/conf.d/3dhubs.conf

#RUN curl -sSL https://raw.githubusercontent.com/wmnnd/nginx-certbot/master/init-letsencrypt.sh | bash

#ENTRYPOINT /kick/entrypoint-web.sh


