LABEL maintainer="dub2sauce@gmail.com"
FROM python:3.6-stretch

RUN apt-get update
RUN apt-get install -y --no-install-recommends supervisor postgresql-client

RUN pip3 install virtualenv
RUN mkdir -p /kick /home/app /home/env
RUN chown 102:1337 /home/env -R

#ADD ./conf/uwsgi.ini /home/app/uwsgi.ini

#ADD ./app /home/app
#WORKDIR /home/app

#RUN bash -c "virtualenv --python=/usr/bin/python3 env && pip3 install -r requirements.txt"

#ENTRYPOINT /kick/entrypoint-web.sh