FROM python:3.6-stretch

RUN apt-get update
RUN apt-get install -y --no-install-recommends supervisor postgresql-client

RUN pip3 install virtualenv
RUN mkdir -p /kick /home/app /home/env
RUN chown 102:1337 /home/env -R